Update Glossary.md to add links for adding terms and requesting explanations
llvm/mlir-www pull request #184
Opened 2024-03-26 17:58 UTC by renxida

2024-03-26 18:04 UTC, ScottTodd requested changes

2024-03-26 18:04 UTC, ScottTodd commented on website/content/getting_started/Glossary.md
> +!!! question - "Something missing?"
I don't think Hugo (which mlir-www uses) supports this style of callout / admonition. IREE docs use mkdocs-material: https://squidfunk.github.io/mkdocs-material/reference/admonitions/.

2024-03-26 18:04 UTC, ScottTodd commented on website/content/getting_started/Glossary.md
> +    Don't see a term here that you think should be? Put it in [here](https://github.com/llvm/mlir-www/blob/main/website/content/getting_started/Glossary.md). Don't know what it means? Submit your ter
Wrap lines at 80 characters

2024-03-26 18:04 UTC, ScottTodd commented on website/content/getting_started/Glossary.md
> +    Don't see a term here that you think should be? Put it in [here](https://github.com/llvm/mlir-www/blob/main/website/content/getting_started/Glossary.md). Don't know what it means? Submit your ter
When abbreviating a link, prefer to pick text with more characters. `here` is just 4 characters, which can be difficult to notice and tap on mobile / click on desktop.

2024-03-26 18:22 UTC, joker-eph commented on website/content/getting_started/Glossary.md
> +    Don't see a term here that you think should be? Put it in [here](https://github.com/llvm/mlir-www/blob/main/website/content/getting_started/Glossary.md). Don't know what it means? Submit your ter
Also the "here" link is pointing to the current page, there is already an "edit this page" link at the bottom

2024-04-01 10:56 UTC, jpienaar commented on website/content/getting_started/Glossary.md
> +[this GitHub Tracking issue](https://github.com/llvm/mlir-www/issues/183) to have it explained.
I'd recommend asking on llvm/llvm-project or Discord rather than on the website. The website is handled by ~2 people on "whenever there is a free moment on a friday" kind of basis while the general community can answer many of these rather well. So asking a question on the more general forums will get faster responses (and be more discoverable until website is updated) and then adding them here is a quick review.

2024-06-04 01:51 UTC, joker-eph requested changes

2024-06-04 01:51 UTC, joker-eph commented on website/content/getting_started/Glossary.md
> +Don't know what it means? Join the [LLVM Discord](https://discord.gg/xS7Z362) and ask in the [#torch-mlir channel](https://discord.com/channels/636084430946959380/742573221882364009)
Why is the Torch MLIR channel mentioned here?

2024-10-17 18:30 UTC, ScottTodd reviewed
(Flushing my review queue) Did you want to continue with this PR? It doesn't look like there's much substance here left.

* "Edit this page" is covered by the existing "edit on github button". Similar text could technically go on all website pages :p
* Join discord and torch-mlir comments are also unrelated

2024-10-18 16:20 UTC, closed without merging

2024-10-18 16:20 UTC, renxida commented
Yup! This should get closed.