Add a new FAQ
llvm/mlir-www pull request #93
Opened 2022-01-26 23:14 UTC by sanjoy

"What is the difference between traits and operation interfaces"

2022-01-26 23:19 UTC, River707 requested changes

2022-01-26 23:19 UTC, River707 commented on website/content/getting_started/Faq.md
> +## What is the difference between traits and operation interfaces?
I would drop the `operation` here (or reword), the same applies for attributes and type traits/interfaces.

2022-01-26 23:19 UTC, River707 commented on website/content/getting_started/Faq.md
> +Both [traits](https://mlir.llvm.org/docs/Traits/) and [operation
Same here. Might want to slight reword references to Op throughout.

2022-01-26 23:28 UTC, joker-eph commented on website/content/getting_started/Faq.md
> +classes with virtual methods.
I'm not sure I understand the analogy with a C++ base class without virtual methods.
For example such C++ base class still allows for polymorphism, that is:

```
void f(BaseClass &b) {
  b.foo(); // calling a non virtual method of the base class independently of the actual operation.
}
```

I don't think a Trait allows for this?

2022-01-27 02:03 UTC, bondhugula commented on website/content/getting_started/Faq.md
> +need a vtable or equivalent while traits don't.  In other words, traits are like
I'm not sure it's useful to reference `vtable` -- that just comes with standard OO polymorphism and is a detail?

2022-01-27 02:03 UTC, bondhugula commented
This FAQ is quite useful to have - thanks!

2022-01-27 06:24 UTC, sanjoy commented on website/content/getting_started/Faq.md
> +need a vtable or equivalent while traits don't.  In other words, traits are like
Removed analogy with C++.

2022-01-27 06:24 UTC, sanjoy commented on website/content/getting_started/Faq.md
> +classes with virtual methods.
Removed analogy with C++.

2022-01-27 21:54 UTC, sanjoy commented
Addressed comments.

2022-01-28 02:00 UTC, joker-eph approved these changes
Thanks! That's a great blob, I love the examples :)

2022-01-28 02:01 UTC, merged